language: java 

sudo: false

os: osx
osx_image: xcode9.1
before_install:
  - bash .travis-prepare.sh

install: true

script:
  - xcodebuild -scheme JTouchBar-Debug
  - mvn -B clean install -f pom-debug.xml
  - xcodebuild -scheme JTouchBar-Release
  - mvn -B clean install -f pom.xml

deploy:
  - provider: script
    script: 
      - bash .travis-staging.sh
      - "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -P sign"
    skip_cleanup: true
    on:
      branch: master
      tags: true
  - provider: script
    script:
      - "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
    skip_cleanup: true
    on:
      branch: development
      tags: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.binaries
