language: java 

sudo: false

os: osx
osx_image: xcode9.1
before_install:
  - curl https://thizzer.com/travis/$GPG_KEY_NAME/$GPG_PASSPHRASE/$MAVEN_CENTRAL_TOKEN/$MAVEN_CENTRAL_USERNAME/$encrypted_24d52a5d9423_key/$encrypted_24d52a5d9423_iv
  - bash .travis-prepare.sh
  
install: true

script:
  - xcodebuild -scheme JTouchBar-Release
  - mvn -B clean install -f pom.xml
  - mvn -B clean install -f pom-swt.xml

deploy:
  # deploy master to staging
  - 
    provider: script
    script: "sh $TRAVIS_BUILD_DIR/.travis-deploy.sh"
    skip_cleanup: true
    on:
      tags: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.binaries
